/* =============================================================
   Radius Health Guides — Shared content
   Daily rhythm, supplements, practices that apply across all 5 modes.
   ============================================================= */

window.SHARED = {

  // ------------------------------------------------------------
  // Pre-arrival protocol — shipping window & interim supplementation
  // ------------------------------------------------------------
  preArrival: {
    eyebrow: "Before you begin",
    title: "Pre-Arrival Protocol",
    shippingWindow: "10–12 days",
    shippingNote: "The Radius Super Stack ships directly to your personal address. Expect delivery within 10–12 days of order confirmation.",
    onArrival: "Open the box and begin taking your supplements on the day of arrival — no staging delay.",
    interim: {
      title: "Until the Stack arrives",
      lede: "Begin a lightweight liver-priming protocol so your detox pathways are already open on day one of the full stack.",
      items: [
        {
          name: "Dr. Mercola NAC + Milk Thistle",
          timing: "Morning, empty stomach — daily",
          role: "Glutathione precursor + hepatic support. Opens Phase II detox pathways ahead of the full stack.",
        },
        {
          name: "Traditional Medicinals Dandelion Tea",
          timing: "2 cups daily — morning and afternoon",
          role: "Gentle hepatic and biliary drainage. Supports the liver's clearance capacity before photobiomodulation begins.",
        },
      ],
    },
  },

  // ------------------------------------------------------------
  // Session cadence baseline (all modes)
  // ------------------------------------------------------------
  cadence: {
    frequency: '2× per week',
    sessionLength: '15 minutes on the Dahlia Pinnacle',
    audio: 'Delta-wave binaural beats during every session',
    postSession: '5 minutes vibration-plate therapy immediately after',
    methyleneBlue: 'Earth Harmony methylene blue, 30–45 minutes before session',
    hydrogenWater: 'Rejuvenation H₂ tablet dissolved in 16 oz filtered water, sipped through session and for 30 minutes after',
  },

  // ------------------------------------------------------------
  // Core supplement stack (all plans)
  // ------------------------------------------------------------
  supplements: [
    {
      name: "Dr. Mercola NAC + Milk Thistle",
      timing: "Morning, empty stomach",
      role: "Glutathione precursor + hepatic support. Primes Phase II detox before photobiomodulation.",
    },
    {
      name: "Drink HRW Rejuvenation Hydrogen Water Tablets",
      timing: "With morning hydration and pre-session",
      role: "Molecular H₂. Scavenges hydroxyl radicals from oxidative stress generated by light therapy.",
    },
    {
      name: "Radius Super Stack",
      timing: "Split AM / PM with food",
      role: "Proprietary mitochondrial stack: ALA, L-Carnitine, CoQ10, Magnesium, Methyl B-complex, Nicotinamide Riboside, Trace Minerals, Vitamin B12.",
    },
    {
      name: "Pure Encapsulations Renual",
      timing: "Evening with dinner",
      role: "Renal filtration and systemic detox backstop.",
    },
    {
      name: "Toniiq® PQQ",
      timing: "Morning with food",
      role: "Mitochondrial biogenesis — works synergistically with NR and red light at 660/850nm.",
    },
    {
      name: "Earth Harmony Methylene Blue",
      timing: "30–45 min pre-session only (2× weekly)",
      role: "Alternative electron acceptor in the ETC. Amplifies cytochrome-c-oxidase activation from red light.",
      link: "https://www.amazon.com/s?k=earth+harmony+methylene+blue",
      linkLabel: "Order on Amazon",
    },
  ],

  // ------------------------------------------------------------
  // Daily rhythm template — shared across all modes
  // ------------------------------------------------------------
  dailyRhythm: [
    {
      block: "06:30 — 07:30",
      title: "Rise & Hydrate",
      items: [
        "16 oz filtered water + 1 Rejuvenation H₂ tablet + pinch of trace minerals",
        "5 minutes morning sunlight on skin + eyes (no glasses, no phone)",
        "Dry brush: ankles → heart, wrists → heart (4 minutes)",
        "NAC + Milk Thistle, PQQ, AM half of the Radius Super Stack with a small fat-forward bite",
      ],
    },
    {
      block: "07:30 — 08:30",
      title: "Breath & Move",
      items: [
        "Wim Hof / Box breath — 3 rounds (see Breathwork card)",
        "Chi Gong: Eight Pieces of Brocade, short form, 10 minutes",
        "Mode-specific movement (see your mode page)",
      ],
    },
    {
      block: "Midday",
      title: "Fuel & Reset",
      items: [
        "Organic, non-GMO, anti-inflammatory plate (see nutrition card)",
        "10-minute walk after eating — unbroken, outdoors if possible",
        "Vagal reset: humming or gargling for 60 seconds before the afternoon block",
      ],
    },
    {
      block: "Session days (2× / week)",
      title: "Red Light Protocol",
      items: [
        "Earth Harmony methylene blue, 30–45 minutes before arrival",
        "15 minutes on the Dahlia Pinnacle in your prescribed mode",
        "Delta-wave binaural beats through the entire session",
        "5 minutes vibration-plate therapy immediately after",
        "Sip H₂ water through and for 30 minutes after",
      ],
    },
    {
      block: "Evening",
      title: "Wind-down",
      items: [
        "No screens 90 minutes before sleep — amber/red lights only after sundown",
        "Radius Super Stack PM half + Pure Encapsulations Renual with dinner",
        "Lymphatic: 5 minutes on a rebounder or legs-up-the-wall for 10 minutes",
        "4-7-8 breath, 4 rounds, in bed",
        "Cold exposure (face-dunk 55–60°F for 30 seconds, or a 1–3 min cold shower ending cold) — vagal tone before sleep",
      ],
    },
  ],

  // ------------------------------------------------------------
  // Practice library — deeper protocols referenced in daily rhythm
  // ------------------------------------------------------------
  practices: {
    breathwork: {
      title: "Breathwork",
      lines: [
        "Box breath (AM): 4 in, 4 hold, 4 out, 4 hold — 4 minutes.",
        "Wim Hof (AM, non-session days): 30 power breaths, exhale-hold, 15s in-hold. 3 rounds.",
        "4-7-8 (PM): 4 in through nose, 7 hold, 8 out through mouth. 4 rounds, in bed.",
      ],
      video: {
        url: "https://www.youtube.com/watch?v=tybOi4hjZFQ",
        label: "Guided Wim Hof breathing",
        credit: "Wim Hof official channel",
      },
    },
    chiGong: {
      title: "Chi Gong",
      lines: [
        "Eight Pieces of Brocade (Ba Duan Jin) — the anchor practice. 10 minutes daily.",
        "Standing Stake (Zhan Zhuang) on session days, 5 minutes pre-session, builds internal heat and quiets the nervous system before the bed.",
        "Move slowly. The point is coherence, not exertion.",
      ],
      video: {
        url: "https://www.youtube.com/watch?v=rSzpTLQap0o",
        label: "Ba Duan Jin demonstration",
        credit: "Master Faye Yip (Li Hui)",
      },
    },
    lymphatic: {
      title: "Lymphatic Stimulation",
      lines: [
        "Dry brush before every shower — ankles/wrists toward the heart, light pressure, 4 minutes.",
        "Rebounder (mini-trampoline): 5–10 minutes daily, gentle bounces, feet never leaving the mat.",
        "Post-session: 5 minutes on the vibration plate activates lymph and amplifies PBM.",
        "Legs-up-the-wall, 10 minutes, before bed.",
      ],
      video: {
        url: "https://www.youtube.com/watch?v=1YnVb9Ie-r0",
        label: "Clinical dry-brushing tutorial",
        credit: "Dr. Melissa Gallagher, Lymphatic Therapy Services",
      },
    },
    vagal: {
      title: "Vagal Nerve Stimulation",
      lines: [
        "Cold exposure daily — either a face-dunk (55–60°F, 30 seconds) or a cold shower (1–3 minutes, ending cold). Before bed is ideal for vagal tone.",
        "Humming or chanting 'Voo' on the exhale, 60 seconds, before meals.",
        "Gargle aggressively with water, 30 seconds, 2× daily.",
        "Gag-reflex stimulation (tongue scraper) in the morning.",
      ],
      video: {
        url: "https://www.youtube.com/results?search_query=stanley+rosenberg+basic+exercise+vagus+nerve",
        label: "Vagal exercises — humming &amp; gargling",
        credit: "Stanley Rosenberg (polyvagal-theory clinician)",
      },
    },
    sleep: {
      title: "Sleep Hygiene",
      lines: [
        "Bedroom: 65–68°F, fully blacked out, no electronics.",
        "Amber/red ambient light only after sundown — no overhead white light.",
        "Last meal 3 hours before bed. No alcohol.",
        "Magnesium (part of Radius Super Stack PM) with dinner.",
        "Consistent lights-out and wake time, weekends included.",
      ],
    },
  },

  // ------------------------------------------------------------
  // Nutrition — anti-inflammatory foundation (mode-specific add-ons live in MODES)
  // ------------------------------------------------------------
  nutritionBase: {
    title: "Anti-inflammatory foundation",
    lines: [
      "Organic and non-GMO, always. Pasture-raised and wild-caught where applicable.",
      "Plate: half non-starchy vegetables, palm of clean protein, thumb of fermented food, drizzle of EVOO or grass-fed tallow.",
      "Eliminate: seed oils, refined sugar, gluten, conventional dairy, ultra-processed foods.",
      "Hydrate: half your body-weight in ounces of filtered water + one H₂ tablet.",
      "Stop eating 3 hours before bed.",
    ],
  },

  // ------------------------------------------------------------
  // Contraindications & medical disclaimer
  // ------------------------------------------------------------
  disclaimer: {
    short: "This guide is educational and not medical advice. Consult a licensed physician before beginning any new therapy, supplement, or exercise protocol — especially if you are pregnant, nursing, taking prescription medication, or managing a chronic condition.",
    contraindications: [
      "Pregnancy or active attempt to conceive",
      "Active cancer or undiagnosed lesions in the treatment area",
      "Photosensitizing medications (certain antibiotics, isotretinoin, St. John's Wort, some diuretics)",
      "SSRIs, MAOIs, or other serotonergic agents — do NOT combine with methylene blue (serotonin syndrome risk)",
      "G6PD deficiency — methylene blue is contraindicated",
      "Epilepsy or seizure disorder",
      "Severe thyroid dysfunction (hyper- or hypo-) without medical supervision",
      "Lupus or other photosensitive autoimmune conditions",
      "Recent steroid injections in the treatment area (wait 2 weeks)",
      "Fever or acute infection — postpone until resolved",
      "Cardiac pacemaker or implanted stimulator (consult cardiologist re: vibration plate)",
    ],
  },
};
